insert into railway.messages values (1,'dmin@gmail.com','Dmitro', 'Thank you for your job');
insert into railway.messages values (2,'sasha@gmail.com','Sasha', 'Thanks for everything!');
insert into railway.messages values (3,'petro@gmail.com','Petro', 'Appreciate your help!');
insert into railway.messages values (4,'kolia@gmail.com','Kolia', 'Great job, thank you!');
insert into railway.messages values (5,'vika@gmail.com','Vika', 'Thank you for your support!');
insert into railway.messages values (6,'marko@gmail.com','Marko', 'You are awesome!');
insert into railway.messages values (7,'katya@gmail.com','Katya', 'Thanks a lot for your assistance!');
insert into railway.messages values (8,'misha@gmail.com','Misha', 'Thank you for your kindness!');
insert into railway.messages values (9,'olya@gmail.com','Olya', 'Your help is much appreciated!');
insert into railway.messages values (10,'dasha@gmail.com','Dasha', 'Thank you so much!');
insert into railway.messages values (11,'igor@gmail.com','Igor', 'Great work, thank you!');
insert into railway.messages values (12,'lena@gmail.com','Lena', 'Thanks for being so helpful!');
insert into railway.messages values (13,'yura@gmail.com','Yura', 'Thank you for your hard work!');
insert into railway.messages values (14,'sophia@gmail.com','Sophia', 'Thank you for your time!');
insert into railway.messages values (15,'nikita@gmail.com','Nikita', 'Your help was invaluable!');
insert into railway.messages values (16,'ira@gmail.com','Ira', 'Thanks for going above and beyond!');
insert into railway.messages values (17,'sergei@gmail.com','Sergei', 'Thank you for your expertise!');
insert into railway.messages values (18,'anna@gmail.com','Anna', 'Thanks for your quick response!');
insert into railway.messages values (19,'max@gmail.com','Max', 'Thank you for being so responsive!');
insert into railway.messages values (20,'ira@gmail.com','Ira', 'Thank you for your attention to detail!');
insert into railway.messages values (21,'artem@gmail.com','Artem', 'Thank you for your support!');
insert into railway.messages values (22,'diana@gmail.com','Diana', 'Thanks for your patience!');
insert into railway.messages values (23,'igor@gmail.com','Igor', 'Thanks for your professionalism!');
insert into railway.messages values (24,'lena@gmail.com','Lena', 'Thank you for your assistance!');
insert into railway.messages values (25,'yura@gmail.com','Yura', 'Thank you for your hard work!');
insert into railway.messages values (26,'sophia@gmail.com','Sophia', 'Thanks for your time!');
insert into railway.messages values (27,'nikita@gmail.com','Nikita', 'Thank you for your invaluable help!');
insert into railway.messages values (28,'ira@gmail.com','Ira', 'Thanks for going above and beyond to help me!');
insert into railway.messages values (29,'sergei@gmail.com','Sergei', 'Thank you for your professionalism!');
insert into railway.messages values (30,'anna@gmail.com','Anna', 'Thanks for your quick response!');
insert into railway.messages values (31,'max@gmail.com','Max', 'Thank you for being so responsive!');
insert into railway.messages values (32,'ira@gmail.com','Ira', 'Thank you for your attention to detail!')
